/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:51:51 EST 2018
 */


import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import main.Movement;
import model.Elevators;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class Movement_ESTest extends Movement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Movement.doMovement();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Movement movement0 = new Movement((Elevators) null);
      // Undeclared exception!
      movement0.run();
  }
}
